title: Shayaan Ahmed Farooqi
email: shayaan.farooqi@gmail.com
description: >- 
  Shayaan Ahmed Farooqi's personal knowledge repository and high quality educational resources aggregation.
  Along with some personal notes / blog posts.
twitter_username: ShayaanFarooqi
github_username: translucent504
minimal_mistakes_skin: contrast

comments:
  provider: "disqus"
  disqus:
    shortname: "translucent504-github-io" 

search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Karachi # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Shayaan Farooqi"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Physics Grad jumping aboard the AI train."
  links:
    - label: "Home"
      icon: "fas fa-fw fa-link"
      url: "https://translucent504.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ShayaanFarooqi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/translucent504"
  #  - label: "Instagram"
   #   icon: "fab fa-fw fa-instagram"
   #   url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ShayaanFarooqi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/translucent504"

defaults:
  # _posts
  - scope:
      path: ""  # This means all files in our site get this layout by default.
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
      #classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true  
  

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
